//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinaGerman.DesktopApplication.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VinaGerman.DesktopApplication.Translations.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear search.
        /// </summary>
        public static string btnClearSearch {
            get {
                return ResourceManager.GetString("btnClearSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon.
        /// </summary>
        public static string btnLogon {
            get {
                return ResourceManager.GetString("btnLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string btnPrint {
            get {
                return ResourceManager.GetString("btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article information.
        /// </summary>
        public static string captionArticleInfo {
            get {
                return ResourceManager.GetString("captionArticleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article List.
        /// </summary>
        public static string captionArticleList {
            get {
                return ResourceManager.GetString("captionArticleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business information.
        /// </summary>
        public static string captionBusinessInfo {
            get {
                return ResourceManager.GetString("captionBusinessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business List.
        /// </summary>
        public static string captionBusinessList {
            get {
                return ResourceManager.GetString("captionBusinessList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string captionCancel {
            get {
                return ResourceManager.GetString("captionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category information.
        /// </summary>
        public static string captionCategoryInfo {
            get {
                return ResourceManager.GetString("captionCategoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category List.
        /// </summary>
        public static string captionCategoryList {
            get {
                return ResourceManager.GetString("captionCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company information.
        /// </summary>
        public static string captionCompanyInfo {
            get {
                return ResourceManager.GetString("captionCompanyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures of company.
        /// </summary>
        public static string captionCompanyPicture {
            get {
                return ResourceManager.GetString("captionCompanyPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string captionConfirm {
            get {
                return ResourceManager.GetString("captionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information.
        /// </summary>
        public static string captionContactInfo {
            get {
                return ResourceManager.GetString("captionContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact List.
        /// </summary>
        public static string captionContactList {
            get {
                return ResourceManager.GetString("captionContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact list.
        /// </summary>
        public static string captionContactListForCompany {
            get {
                return ResourceManager.GetString("captionContactListForCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string captionCustomer {
            get {
                return ResourceManager.GetString("captionCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer list.
        /// </summary>
        public static string captionCustomerList {
            get {
                return ResourceManager.GetString("captionCustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department information.
        /// </summary>
        public static string captionDepartmentInfo {
            get {
                return ResourceManager.GetString("captionDepartmentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department List.
        /// </summary>
        public static string captionDepartmentList {
            get {
                return ResourceManager.GetString("captionDepartmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string captionDetail {
            get {
                return ResourceManager.GetString("captionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string captionError {
            get {
                return ResourceManager.GetString("captionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry information.
        /// </summary>
        public static string captionIndustryInfo {
            get {
                return ResourceManager.GetString("captionIndustryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry List.
        /// </summary>
        public static string captionIndustryList {
            get {
                return ResourceManager.GetString("captionIndustryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string captionInformation {
            get {
                return ResourceManager.GetString("captionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location information.
        /// </summary>
        public static string captionLocationInfo {
            get {
                return ResourceManager.GetString("captionLocationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location List.
        /// </summary>
        public static string captionLocationList {
            get {
                return ResourceManager.GetString("captionLocationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string captionLogon {
            get {
                return ResourceManager.GetString("captionLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string captionNo {
            get {
                return ResourceManager.GetString("captionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string captionOK {
            get {
                return ResourceManager.GetString("captionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Info.
        /// </summary>
        public static string captionOrderInfo {
            get {
                return ResourceManager.GetString("captionOrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order list.
        /// </summary>
        public static string captionOrderList {
            get {
                return ResourceManager.GetString("captionOrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related article list.
        /// </summary>
        public static string captionRelatedArticle {
            get {
                return ResourceManager.GetString("captionRelatedArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string captionSearch {
            get {
                return ResourceManager.GetString("captionSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result.
        /// </summary>
        public static string captionSearchResult {
            get {
                return ResourceManager.GetString("captionSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string captionSupplier {
            get {
                return ResourceManager.GetString("captionSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier list.
        /// </summary>
        public static string captionSupplierList {
            get {
                return ResourceManager.GetString("captionSupplierList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string captionYes {
            get {
                return ResourceManager.GetString("captionYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article No.
        /// </summary>
        public static string hintArticleSearch {
            get {
                return ResourceManager.GetString("hintArticleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string hintCategorySearch {
            get {
                return ResourceManager.GetString("hintCategorySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name/Phone/Tax Code.
        /// </summary>
        public static string hintCompanySearch {
            get {
                return ResourceManager.GetString("hintCompanySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName/Email/Phone/Adress.
        /// </summary>
        public static string hintContactSearch {
            get {
                return ResourceManager.GetString("hintContactSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone/Description.
        /// </summary>
        public static string hintDepartmentSearch {
            get {
                return ResourceManager.GetString("hintDepartmentSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address/Description.
        /// </summary>
        public static string hintLocationSearch {
            get {
                return ResourceManager.GetString("hintLocationSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNumber/Description.
        /// </summary>
        public static string hintOrderSearch {
            get {
                return ResourceManager.GetString("hintOrderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article:.
        /// </summary>
        public static string lblArticle {
            get {
                return ResourceManager.GetString("lblArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArticleNo:.
        /// </summary>
        public static string lblArticleNo {
            get {
                return ResourceManager.GetString("lblArticleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit:.
        /// </summary>
        public static string lblArticleUnit {
            get {
                return ResourceManager.GetString("lblArticleUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business:.
        /// </summary>
        public static string lblBusiness {
            get {
                return ResourceManager.GetString("lblBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business name:.
        /// </summary>
        public static string lblBusinessName {
            get {
                return ResourceManager.GetString("lblBusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        public static string lblCategory {
            get {
                return ResourceManager.GetString("lblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission:.
        /// </summary>
        public static string lblCommission {
            get {
                return ResourceManager.GetString("lblCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company code:.
        /// </summary>
        public static string lblCompanyCode {
            get {
                return ResourceManager.GetString("lblCompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name:.
        /// </summary>
        public static string lblCompanyName {
            get {
                return ResourceManager.GetString("lblCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        public static string lblContact {
            get {
                return ResourceManager.GetString("lblContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer:.
        /// </summary>
        public static string lblCustomer {
            get {
                return ResourceManager.GetString("lblCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department:.
        /// </summary>
        public static string lblDepartment {
            get {
                return ResourceManager.GetString("lblDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee:.
        /// </summary>
        public static string lblEmployee {
            get {
                return ResourceManager.GetString("lblEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free text:.
        /// </summary>
        public static string lblFreeTextSearch {
            get {
                return ResourceManager.GetString("lblFreeTextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name:.
        /// </summary>
        public static string lblFullName {
            get {
                return ResourceManager.GetString("lblFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry:.
        /// </summary>
        public static string lblIndustry {
            get {
                return ResourceManager.GetString("lblIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry name:.
        /// </summary>
        public static string lblIndustryName {
            get {
                return ResourceManager.GetString("lblIndustryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location name:.
        /// </summary>
        public static string lblLocationName {
            get {
                return ResourceManager.GetString("lblLocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order date:.
        /// </summary>
        public static string lblOrderDate {
            get {
                return ResourceManager.GetString("lblOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number:.
        /// </summary>
        public static string lblOrderNumber {
            get {
                return ResourceManager.GetString("lblOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay date:.
        /// </summary>
        public static string lblPayDate {
            get {
                return ResourceManager.GetString("lblPayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string lblPort {
            get {
                return ResourceManager.GetString("lblPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        public static string lblPosition {
            get {
                return ResourceManager.GetString("lblPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        public static string lblPrice {
            get {
                return ResourceManager.GetString("lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity:.
        /// </summary>
        public static string lblQuantity {
            get {
                return ResourceManager.GetString("lblQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining quantity:.
        /// </summary>
        public static string lblRemainQuantity {
            get {
                return ResourceManager.GetString("lblRemainQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        public static string lblServer {
            get {
                return ResourceManager.GetString("lblServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier:.
        /// </summary>
        public static string lblSupplier {
            get {
                return ResourceManager.GetString("lblSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax code:.
        /// </summary>
        public static string lblTaxCode {
            get {
                return ResourceManager.GetString("lblTaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName:.
        /// </summary>
        public static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website:.
        /// </summary>
        public static string lblWebsite {
            get {
                return ResourceManager.GetString("lblWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this item?.
        /// </summary>
        public static string msgConfirmDelete {
            get {
                return ResourceManager.GetString("msgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to quit?.
        /// </summary>
        public static string msgConfirmQuit {
            get {
                return ResourceManager.GetString("msgConfirmQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save?.
        /// </summary>
        public static string msgConfirmSave {
            get {
                return ResourceManager.GetString("msgConfirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string msgLoading {
            get {
                return ResourceManager.GetString("msgLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string msgSaving {
            get {
                return ResourceManager.GetString("msgSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string ORDERSTATUS_APPROVED {
            get {
                return ResourceManager.GetString("ORDERSTATUS_APPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed.
        /// </summary>
        public static string ORDERSTATUS_PROCESSED {
            get {
                return ResourceManager.GetString("ORDERSTATUS_PROCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string ORDERSTATUS_READY {
            get {
                return ResourceManager.GetString("ORDERSTATUS_READY", resourceCulture);
            }
        }
    }
}
